name: video_player_task
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  chewie: ^1.5.0
  cloud_firestore: ^4.8.1
  cupertino_icons: ^1.0.2
  encrypt: ^5.0.1
  firebase_auth: ^4.6.3
  firebase_core: ^2.14.0
  firebase_storage: ^11.2.3
  flutter:
    sdk: flutter
  flutter_file_downloader: ^1.1.2
  flutter_windowmanager: ^0.2.0
  fluttertoast: ^8.2.2
  get: 4.6.5
  image_picker: ^0.8.9
  intl: ^0.18.1
  path_provider: ^2.0.15
  permission_handler: ^10.3.0
  shared_preferences: ^2.1.2
  video_player: ^2.6.1

dev_dependencies:
  flutter_lints: 2.0.1
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
