// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAyqbr5BABhv0RAuDxZ28wEk7fst43qy2A',
    appId: '1:452077607980:web:01bac2fbf6e608018f4589',
    messagingSenderId: '452077607980',
    projectId: 'lilacinfotech-3b218',
    authDomain: 'lilacinfotech-3b218.firebaseapp.com',
    storageBucket: 'lilacinfotech-3b218.appspot.com',
    measurementId: 'G-BSTZFRP3QG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA5o_kyh9aMiTIw9YbPcYsw14c0BULe1Js',
    appId: '1:452077607980:android:3d58bb8452b6d7538f4589',
    messagingSenderId: '452077607980',
    projectId: 'lilacinfotech-3b218',
    storageBucket: 'lilacinfotech-3b218.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAvNlOtUZsSRCUWNkCEyBIFlTS0mtmwDeI',
    appId: '1:452077607980:ios:068b6fb372a7595b8f4589',
    messagingSenderId: '452077607980',
    projectId: 'lilacinfotech-3b218',
    storageBucket: 'lilacinfotech-3b218.appspot.com',
    androidClientId: '452077607980-5jlatt7qlheppbnvnap52a3sctampuuh.apps.googleusercontent.com',
    iosClientId: '452077607980-5iqoiuffkbvnpp0efs3120agsp5ib5ci.apps.googleusercontent.com',
    iosBundleId: 'com.lilacinfotech.videoPlayer',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAvNlOtUZsSRCUWNkCEyBIFlTS0mtmwDeI',
    appId: '1:452077607980:ios:f98a8eb8954a007f8f4589',
    messagingSenderId: '452077607980',
    projectId: 'lilacinfotech-3b218',
    storageBucket: 'lilacinfotech-3b218.appspot.com',
    androidClientId: '452077607980-5jlatt7qlheppbnvnap52a3sctampuuh.apps.googleusercontent.com',
    iosClientId: '452077607980-r1dcdr7jpjg9tnauhgf6v4jftsemh54q.apps.googleusercontent.com',
    iosBundleId: 'com.lilacinfotech.videoPlayer.RunnerTests',
  );
}
